### ISSUE TITLE
Travis CI failing

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/cyavro-feedstock#2]
Apparently Travis CI is failing even though OS X builds are skipped. This appears to have to do with the missing NumPy version setting. See the [log](https://travis-ci.org/conda-forge/cyavro-feedstock#L368). We have two options.
1. Disable Travis CI.
2. Add a dummy NumPy version.
3. Ignore as we are not building there.

IMHO this is as good a time as any to do 1. Thoughts @pelson?

**Comment by mariusvniekerk** [comment]
Disabling travis seems easy enough for now

**Comment by jakirkham** [comment]
The plan is actually to make this happen automatically. See this issue ( https://github.com/conda-forge/conda-smithy/issues/205 ). Half of this has already been merged. The other half is proposed, but we are having some issues with the Travis CI API.

**Comment by jakirkham** [comment]
See PR ( https://github.com/conda-forge/cyavro-feedstock/pull/3 ) for the applied fix to this.

**Comment by mariusvniekerk** [comment]
Thanks @jakirkham
